# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('crc32', models.BigIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('character', models.CharField(blank=True, max_length=16, null=True)),
                ('achievements', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='highscores.GameMode')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highscores.Version'),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highscores.Version'),
        ),
        migrations.AddField(
            model_name='checksum',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highscores.Version'),
        ),
    ]
