# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
